Vagrant.require_version ">= 2.0.0"

VM_IMG = "ubuntu/focal64"
VM_NAME = "ubuntu2004-vagrants"
VM_MEM = ENV["VM_MEM"] || 4096

system("
    if [ #{ARGV[0]} = 'up' ]; then
      if [ ! -f ~/.ssh/id_rsa ]; then
        echo '~/.ssh/id_rsa keys does not exist.'
        ssh-keygen -t rsa -f ~/.ssh/id_rsa
      fi
    fi
")

Vagrant.configure("2") do |config|
  # vagrant@VM_NAME
  config.vm.hostname = VM_NAME

  config.vm.define VM_NAME do |cfg|
    cfg.vm.box = VM_IMG
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = VM_NAME
      vb.memory = VM_MEM
      vb.cpus = 2
      vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
    end
  end

  # copy ssh keys
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
  config.vm.provision :shell, :inline => "cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys", run: "always"

  # private network
  config.vm.network "private_network", type: "dhcp"

end
